### ISSUE TITLE
Android build issues

### ISSUE THREAD

**Issue by reinierkops** [tranb3r/secure-httpclient#11]
Get the following error while compiling my project with this

COMPILETODALVIK: Error: com.android.dx.cf.code.SimException: invalid opcode ba (invokedynamic requires --min-sdk-version >= 26) Uncaught translation.

**Comment by tranb3r** [comment]
I think you need to add `<AndroidDexTool>d8</AndroidDexTool>` into the csproj of your android project.

**Comment by tranb3r** [comment]
@reinierkops Any progress?
