### ISSUE TITLE
[Question] How trusted roots and pins work together?

### ISSUE THREAD

**Issue by alexrainman** [tranb3r/secure-httpclient#8]
When you provide a trusted root, is it used instead of the provided pins?

**Comment by alexrainman** [comment]
I understand now ho it works on iOS https://github.com/tranb3r/secure-httpclient/blob/master/SecureHttpClient/Platforms/iOS/DataTaskDelegate.cs#L151

What happen in Android if you don't provide TrustedRoots?

**Comment by tranb3r** [comment]
I'm not sure I understand your question.
Maybe it's easier to test and see if it fits your use-case ?

**Comment by alexrainman** [comment]
No worries, I got it.
